version: '3.8'
name: obtainadex

services:
  webapp:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile
    image: obtainadex-webapp
    restart: always
    ports:
      - '3003:3000'
    command: sh -c "npm run start"
