# deploys to GitHub Pages when pushed to main branch
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build the application
        run: cd obtainadex && deno task build

      - name: Upload dist directory
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: obtainadex/dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download dist directory
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist/

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: LukeHollandDev/LukeHollandDev.github.io
          branch: main
          folder: dist/
          target-folder: obtainadex
          clean: true
          token: ${{ secrets.PAT }}
